// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table NNNN (SalesOrderID:string, OrderDate:datetime, CustomerID:string, LineItem:long, ProductID:string, OrderQty:long, LineItemTotal:real) 
.create-or-alter table NNNN ingestion csv mapping 'NNNN_mapping'
```
[{"Properties":{"Ordinal":"0"},"column":"SalesOrderID","datatype":""},{"Properties":{"Ordinal":"1"},"column":"OrderDate","datatype":""},{"Properties":{"Ordinal":"2"},"column":"CustomerID","datatype":""},{"Properties":{"Ordinal":"3"},"column":"LineItem","datatype":""},{"Properties":{"Ordinal":"4"},"column":"ProductID","datatype":""},{"Properties":{"Ordinal":"5"},"column":"OrderQty","datatype":""},{"Properties":{"Ordinal":"6"},"column":"LineItemTotal","datatype":""}]
```
